### ISSUE TITLE
Colours are strange one Fantasy section

### ISSUE THREAD

**Issue by CyborgCabbage** [Lopeh/onepiece-place#46]
![image](https://user-images.githubusercontent.com/29862837/161454443-dec1f506-ff5d-42e9-ba6c-769bba3883ab.png)
![image](https://user-images.githubusercontent.com/29862837/161454472-19ffcc01-35aa-4733-8417-c408329ca72b.png)

**Comment by Lopeh** [comment]
Latest color corrections have been pushed. Thanks for the heads up!
